<?php

/** 
* Provides the functions for the computed field DLL Page Link.
* @author Samuel J. Huskey (huskey@ou.edu)
*/

function computed_field_field_dll_page_link_compute(&$entity_field, $entity_type, $entity, $field, $instance, $langcode, $items) {
    $entity_field[0]['value'] = 'value';
	
	$author_name = $entity->field_authorized_name['und'][0]['value'];
	$identifier = $entity->field_dll_identifier['und'][0]['value'];
	$work_name = $entity->field_work_name['und'][0]['value'];

	// Generate the output URL based on content type.
	if ($entity->type == 'author_authorities') {
		$output = '<a href="https://catalog.digitallatin.org/dll-author' . $identifier . '">https://catalog.digitallatin.org/dll-author/' .$identifier . '</a>';
		}
	elseif ($entity->type == 'dll_work') {
		$output = '<a href="https://catalog.digitallatin.org/dll-work/' . $identifier . '">https://catalog.digitallatin.org/dll-work/' .$identifier . '</a>';
		}
	elseif ($entity->type == 'repository_item') {
		$output = '<a href="https://catalog.digitallatin.org/dll-item-record/' . $identifier . '">https://catalog.digitallatin.org/dll-item-record/' .$identifier . '</a>';
		}
	elseif ($entity->type == 'web_page') {
		$output = '<a href="https://catalog.digitallatin.org/dll-web-page/' . $identifier . '">https://catalog.digitallatin.org/dll-web-page/' .$identifier . '</a>';
		}
	else {
		return;
		}
    $entity_field[0]['value'] = $output;
}

function computed_field_field_dll_page_link_display($field, $entity_field_item, $entity_lang, $langcode, $entity) {
    //$display_output = $entity_field_item['value'];
	return $entity_field_item['value'];
}
