<?php

/** 
* Provides the functions for the computed field DLL Author ID.
* The DLL Identifier must be a unique identifier based on the node ID of a node
* of type Author Authorities, DLL Work, Repository Item, or Web Page.
*
* @author Samuel J. Huskey (huskey@ou.edu)
*/

function computed_field_field_dll_identifier_compute(&$entity_field, $entity_type, $entity, $field, $instance, $langcode, $items) {
    $entity_field[0]['value'] = 'value';

// Define variables for the authorized name and the nid.
	$identifier = $entity->field_dll_number['und'][0]['value'];
	 
// Generate the output.
	if ($entity->type == 'author_authorities') {
		$output = 'dllcat:A' . $identifier;
		}
	elseif ($entity->type == 'dll_work') {
		$output = 'dllcat:W' . $identifier;
		}
	elseif ($entity->type == 'repository_item') {
		$output = 'dllcat:IR' . $identifier;
		}
	elseif ($entity->type == 'web_page') {
		$output = 'dllcat:WP' . $identifier;
		}
	else {
		$output = $identifier;
		}
    $entity_field[0]['value'] = $output;
}

function computed_field_field_dll_identifier_display($field, $entity_field_item, $entity_lang, $langcode, $entity) {
    //$display_output = $entity_field_item['value'];
	return $entity_field_item['value'];
}
